// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	secretsmanager "github.com/aws/aws-sdk-go/service/secretsmanager"
	mock "github.com/stretchr/testify/mock"
)

// SM is an autogenerated mock type for the Client type
type SM struct {
	mock.Mock
}

// GetSecretValue provides a mock function with given fields: _a0
func (_m *SM) GetSecretValue(_a0 *secretsmanager.GetSecretValueInput) (*secretsmanager.GetSecretValueOutput, error) {
	ret := _m.Called(_a0)

	var r0 *secretsmanager.GetSecretValueOutput
	if rf, ok := ret.Get(0).(func(*secretsmanager.GetSecretValueInput) *secretsmanager.GetSecretValueOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*secretsmanager.GetSecretValueOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*secretsmanager.GetSecretValueInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
