name: tests
on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Init
        uses: actions/setup-go@master
        with:
          go-version: 1.14
        id: go

      - name: Checkout
        uses: actions/checkout@master

      - name: Install Dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Lint
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
          golangci-lint run ./...

      - name: Test
        run: go test -v $(go list ./... | grep -v vendor | grep -v mocks) -race -coverprofile=coverage.txt -covermode=atomic
